### ISSUE TITLE
Create bot in system tab displays a language key of this extension

### ISSUE THREAD

**Issue by Galixte** [satanasov/birthdaycontrol#10]
Hi @satanasov,

i was in system tab to create a new bot and when i validated the new bot, this message was displayed:
“Veuillez sélectionner votre date d’anniversaire. Cette information est obligatoire pour s’enregistrer.”

This text  come from the FRENCH translation of your extension:
```
'BDAY_NO_DATE'	=> 'Veuillez sélectionner votre date d’anniversaire. Cette information est obligatoire pour s’enregistrer.',
```

What’s wrong in your extension ?

**Comment by satanasov** [comment]
Fixed. Adding user wanted Birthday, but why setting birthday to bot? 

Fixed in 026820d39430f059e410db22d3cc11dfd46b2e3c
