### ISSUE TITLE
The extension does not show up in php 3.1.3

### ISSUE THREAD

**Issue by everflux** [satanasov/birthdaycontrol#2]
After adding a clone of the repo to the "ext" directory I expected to have the extension ready for installation through the ACP. But it was not shown. Other extensions work.
Is there something special to do?

**Comment by satanasov** [comment]
This extension resides in anavaro folder in ext.

Namespace is ext/author/name - so ext/anavaro/birthdaycontrol

**Comment by everflux** [comment]
That fixed the issue indeed, thank you!
