### ISSUE TITLE
“YES” and “NO” texts are displayed on UCP and registration pages for other languages than english

### ISSUE THREAD

**Issue by Galixte** [satanasov/birthdaycontrol#7]
Hi @satanasov,

on the registration page with FRENCH language as default board language i can see “Afficher votre âge :” (equivalent language key in ENGLISH is “Show age”), it’s OK but the choice is displayed in english, like that: “Yes”  “No”.

Same issue on UCP page.

Why it’s not displayed in french ?

-------------------

Second issue, on my same board, if a guest user chooses english for language to displaying (there is a menu box to choose the language to displaying for all users - Quicklanguage extension) the text “Show age” on the registration page is displayed in FRENCH language like “Afficher votre âge:” instead of “Show age”. My default language board is FRENCH of course.

**Comment by satanasov** [comment]
Hard coded language parameter. 

phpBB does not allow CPFs to have custom language. Sorry but you will have to change it manualy from ACP.
